### ISSUE TITLE
issues with deposit

### ISSUE THREAD

**Issue by norfolkpine** [nitantchhajed/op-stack-bridge#8]
TypeError: Cannot read properties of undefined (reading 'address')
    at toAddress (coercion.ts:109:1)
    at new StandardBridgeAdapter (standard-bridge.ts:58:1)
    at getBridgeAdapters (contracts.ts:258:1)
    at new CrossChainMessenger (cross-chain-messenger.ts:181:1)
    at handleDeposit (Deposit.js:118:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)

**Comment by norfolkpine** [comment]
Fixed by adding this to the .env file:
REACT_APP_L2_BRIDGE = 0x4200000000000000000000000000000000000010

**Comment by nitantchhajed** [comment]
Thanks for adding it. I will update the .env

**Comment by nitantchhajed** [comment]
Check out the latest commit !
